import {build} from 'esbuild';
import {mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {basename, dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createReactAriaIOSBlurCompat, createReactAriaSlotContainmentCompat} from './react-aria-compat.mjs';

const root = dirname(fileURLToPath(import.meta.url));
const temporary = mkdtempSync(join(tmpdir(), 'maison-react-'));
const check = process.argv.includes('--check');

const modules = [
  {
    entry: join(root, 'src/app.jsx'),
    compiled: join(temporary, 'maison-react.js'),
    output: join(root, '../../config/www/maison/vendor/maison-react.js'),
    requiredExport: 'mountDashboard',
  },
  {
    entry: join(root, 'src/gallery.jsx'),
    compiled: join(temporary, 'maison-gallery.js'),
    output: join(root, '../../config/www/maison/vendor/maison-gallery.js'),
    requiredExport: 'mountGallery',
  },
];
// The licences shipped beside the bundles, each copied verbatim from one
// package and covering the packages it names (`@scope/*` names a scope).
// Every package with bytes in a bundle must be covered by one, and its own
// licence text must be the shipped one: assertLicensed() fails the build
// otherwise, so a new transitive dependency can't ship without its licence.
const licenses = [
  {
    source: join(root, 'node_modules/react/LICENSE'),
    output: join(root, '../../config/www/maison/vendor/LICENSE.React.txt'),
    packages: ['react', 'react-dom', 'scheduler', 'use-sync-external-store'],
  },
  {
    source: join(root, 'node_modules/react-aria/LICENSE'),
    output: join(root, '../../config/www/maison/vendor/LICENSE.React-Aria.txt'),
    packages: ['react-aria', 'react-aria-components', 'react-stately', '@internationalized/*'],
  },
  {
    source: join(root, 'node_modules/clsx/license'),
    output: join(root, '../../config/www/maison/vendor/LICENSE.clsx.txt'),
    packages: ['clsx'],
  },
];
const sameText = (left, right) => left.replace(/\r\n?/g, '\n').trim() === right.replace(/\r\n?/g, '\n').trim();

// Each package with bytes in a bundle, read from its metafile (input paths
// are relative to the working directory, the package being the one after
// the last node_modules), held to the licence that covers it.
function assertLicensed(metafile, output) {
  const packages = new Map();
  for (const [input, {bytesInOutput}] of Object.values(metafile.outputs).flatMap(item => Object.entries(item.inputs))) {
    const found = bytesInOutput > 0 && input.match(/^(.*node_modules\/((?:@[^/]+\/)?[^/]+))\//);
    if (found) packages.set(found[2], resolve(found[1]));
  }
  for (const [name, directory] of packages) {
    const license = licenses.find(item => item.packages.some(covered => covered === name || (covered.endsWith('/*') && name.startsWith(covered.slice(0, -1)))));
    if (!license) throw new Error(`${basename(output)} bundles ${name}, which no shipped licence covers`);
    const own = readdirSync(directory).find(file => /^licen[cs]e(?:\.|$)/i.test(file));
    if (!own || !sameText(readFileSync(join(directory, own), 'utf8'), readFileSync(license.source, 'utf8')))
      throw new Error(`${basename(output)} bundles ${name}, whose licence is not ${basename(license.output)}'s`);
  }
}

try {
  const generated = [];
  for (const module of modules) {
    const reactAriaCompat = createReactAriaSlotContainmentCompat(root);
    const iosBlurCompat = createReactAriaIOSBlurCompat(root);
    const result = await build({
      entryPoints: [module.entry],
      outfile: module.compiled,
      bundle: true,
      format: 'esm',
      platform: 'browser',
      target: ['es2022'],
      jsx: 'automatic',
      minify: true,
      treeShaking: true,
      legalComments: 'eof',
      sourcemap: false,
      metafile: true,
      plugins: [reactAriaCompat.plugin, iosBlurCompat.plugin],
      define: {
        'process.env.NODE_ENV': '"production"',
      },
      banner: {
        js: `/* Generated by frontend/maison/build-app.mjs. Do not edit directly.
 * MODIFIED REACT ARIA SOURCE NOTICE: this bundle contains a build-time
 * modification to React Aria 3.52.1 DOMFunctions.mjs so slotted containment
 * visits the assigned slot before its ancestors. See LICENSE.React-Aria.txt.
 * usePreventScroll.mjs also limits the iOS keyboard-Done blur fallback to
 * keyboard-opening fields, preserving nested dialog accessibility refocusing.
 */`,
      },
      logLevel: 'warning',
    });
    reactAriaCompat.assertApplied(result.metafile);
    iosBlurCompat.assertApplied(result.metafile);
    assertLicensed(result.metafile, module.output);

    const moduleSource = readFileSync(module.compiled, 'utf8');
    // Each bundle exports exactly its one entry point, as its metafile says.
    const exports = Object.values(result.metafile.outputs).flatMap((item) => item.exports);
    if (exports.length !== 1 || exports[0] !== module.requiredExport) {
      throw new Error(`Maison React bundle exports ${JSON.stringify(exports)}, not exactly ${module.requiredExport}`);
    }
    const runtimeImports = Object.values(result.metafile.outputs).flatMap((item) => item.imports);
    if (runtimeImports.length) {
      throw new Error(`Maison React bundle contains a runtime module dependency: ${module.output}`);
    }
    generated.push({...module, moduleSource});
  }

  if (check) {
    const stale = generated
      .filter((module) => readFileSync(module.output, 'utf8') !== module.moduleSource)
      .map((module) => module.output);
    for (const license of licenses) {
      if (readFileSync(license.output, 'utf8') !== readFileSync(license.source, 'utf8')) {
        stale.push(license.output);
      }
    }
    if (stale.length) {
      throw new Error(`Generated Maison React bundles are stale: ${stale.join(', ')}`);
    }
    console.log('Maison React bundles are current.');
  } else {
    for (const module of generated) {
      writeFileSync(module.output, module.moduleSource);
      console.log(`Wrote ${module.output}`);
    }
    for (const license of licenses) {
      writeFileSync(license.output, readFileSync(license.source, 'utf8'));
      console.log(`Wrote ${license.output} (${license.packages.join(', ')})`);
    }
  }
} finally {
  rmSync(temporary, {recursive: true, force: true});
}
