// Generate a small, offline subset of the Gravity UI, Lucide and Phosphor icon families.
import {readFile, writeFile} from 'node:fs/promises';
const root = new URL('../../', import.meta.url);
const sets = {};
for (const name of ['gravity-ui','lucide','ph']) sets[name] = JSON.parse(await readFile(new URL(`node_modules/@iconify-json/${name}/icons.json`,import.meta.url),'utf8'));
const gravity = {home:'house',rooms:'layout-cells-large',energy:'thunderbolt',life:'calendar',settings:'sliders',sun:'sun',moon:'moon',cloud:'cloud',desk:'display',power:'power',arrow:'arrow-right',chevron:'chevron-right',close:'xmark',check:'check',alert:'triangle-exclamation',vacuum:'face-robot',plug:'plug-connection',lock:'lock',bin:'trash-bin',paper:'file',pause:'pause',start:'play',dock:'house',droplet:'droplet',search:'magnifier',minus:'minus',plus:'plus',info:'circle-info',chart:'chart-line',music:'music-note',clock:'clock',refresh:'arrows-rotate-right',motion:'person',signal:'antenna-signal'};
const lucide = {climate:'thermometer',rain:'cloud-rain',sofa:'sofa',kitchen:'cooking-pot',dining:'utensils',stairs:'footprints',toys:'toy-brick',bed:'bed-double',bath:'bath',battery:'battery',car:'car',recycle:'recycle',leaf:'leaf',grid:'utility-pole',
  // Maison's weather (the forecast days' icons) and the house node on Energy's header chart (#29).
  'wx-sun':'sun','wx-moon':'moon','wx-partly':'cloud-sun','wx-partly-night':'cloud-moon','wx-cloud':'cloud','wx-rain':'cloud-rain',
  'wx-snow':'cloud-snow','wx-fog':'cloud-fog','wx-storm':'cloud-lightning','wx-wind':'wind','wx-hail':'cloud-hail','wx-house':'house'};
// The phone tab bar's glyphs: filled, as iOS draws a tab bar, and one family
// so the four share a weight.
const phosphor = {'tab-today':'house-fill','tab-climate':'thermometer-simple-fill','tab-car':'car-fill','tab-energy':'lightning-fill'};
const icons = {};
for (const [set, aliases] of [['gravity-ui',gravity],['lucide',lucide],['ph',phosphor]]) for (const [alias,name] of Object.entries(aliases)) {
  const data=sets[set], item=data.icons[name];
  if(!item) throw new Error(`Missing ${set}:${name}`);
  icons[alias]={body:item.body,width:item.width||data.width||16,height:item.height||data.height||16,set,name};
}
const output=`// Generated by frontend/maison/build-icons.mjs; do not edit paths by hand.\n// Gravity UI (MIT) + Lucide (ISC/MIT) + Phosphor (MIT). See vendor/LICENSE.*-Icons.txt.\nconst icons = ${JSON.stringify(icons,null,2)};\nexport const iconNames = Object.freeze(Object.keys(icons));\nexport function icon(name, cls='') {\n  const item=icons[name]||icons.info;\n  const safeClass=String(cls).replace(/[^a-zA-Z0-9_ -]/g,'');\n  return \`<svg class="icon \${safeClass}" data-icon="\${item.set}:\${item.name}" viewBox="0 0 \${item.width} \${item.height}" fill="currentColor" stroke="none" aria-hidden="true" focusable="false">\${item.body}</svg>\`;\n}\n`;
const path=new URL('config/www/maison/icons.js',root);
if(process.argv.includes('--check')) {if(await readFile(path,'utf8')!==output)throw new Error('Icon bundle is out of date'); console.log(`${Object.keys(icons).length} local icons verified`);}
else {await writeFile(path,output);console.log(`${Object.keys(icons).length} local icons generated`);}
